### PR TITLE
React Rewrite

### PR DESCRIPTION
**Pull request by BobDotCom**
# React Rewrite
Discussed in #38, this PR rewrites the site in react.

I chose Next.js because it's a very well known framework for react with a lot of nice features. Additionally, it's used on countless websites for major companies including Netflix, TikTok, Twitch, Hulu, Notion, Target, etc. ([Next.js Showcase](https://nextjs.org/showcase))

I also used tailwind CSS, another extremely widely used framework featured on the websites of ChatGPT / OpenAI, Netflix, and even NASA. ([Tailwind CSS Showcase](https://tailwindcss.com/showcase))

Currently, upon creating this PR, I only implemented the index page. The other pages are currently served through Next.js as static files, so they still work as previously but haven't been migrated yet.

For development instructions, see `README-nextjs.md`.

## TODO
- Finish index page
  - [x] Migrate all CSS to inline tailwind
  - [x] Fix styling at the bottom of the page
  - [x] Make responsive, if necessary.
- Finish puzzle pages
  - [x] LockPick
    - [x] Laundromat
  - [x] RepairKit
  - [x] RoofRunning
  - [ ] SmokeCrack
  - [ ] Word Memory (new)

## Before/After

<details>
<summary>Index</summary>

| Before | After |
| ---       | ---    |
| Screenshot 2024-02-27 at 6 42 05 PM | Screenshot 2024-02-27 at 6 38 06 PM |

</details>

<details>
<summary>Repair Kit</summary>

| Before | After |
| ---       | ---    |
| Screenshot 2024-02-27 at 6 43 36 PM | Screenshot 2024-02-27 at 6 45 07 PM |

</details>

### CODE REVIEW

**Comment by BobDotCom** [comment]
Closes #42

**Comment by BobDotCom** [comment]
I've published my fork to vercel, and it is currently deployed from the `react` branch so you can visit that to see the changes from this PR: https://nopixel.vercel.app/

**Comment by MaximilianAdF** [comment]
> I've published my fork to vercel, and it is currently deployed from the `react` branch so you can visit that to see the changes from this PR: https://nopixel.vercel.app/

That is great. Do you think it is beneficial to transition over to Vercel compared to Github Pages in general?

**Comment by BobDotCom** [comment]
> > I've published my fork to vercel, and it is currently deployed from the `react` branch so you can visit that to see the changes from this PR: https://nopixel.vercel.app/
> 
> That is great. Do you think it is beneficial to transition over to Vercel compared to Github Pages in general?

@MaximilianAdF Yeah, I'd say so. Next.js is created by vercel, so their platform is totally optimized for it. Additionally, the free plan includes edge network, so some server-side JS code can run. 

A couple other things:

1. Feel free to ask if there's any part of the code that you're unsure about. You mentioned that you didn't know too much react yet, and I did try to put a lot of comments in the code, but I didn't put them everywhere.
2. On another note, this isn't completely finished, but it's probably ready to merge. The SmokeCrack hack hasn't been rewritten in React yet, and there's a couple other things I wanted to do, but those can be done later. I think it'd be worth it to merge this PR now (so the word memory hack is available), and the other stuff can be finished in another PR.
3. Do you have a discord account? I typically find it easier to communicate there.
4. If you want, I could help you setup the vercel integration and stuff as well. I'd probably need you to give me access to the repository though, so its up to you if you want to do that.

**Comment by MaximilianAdF** [comment]
@BobDotCom 
Sorry for the extremely late response, I have been busy lately and have also been experimenting a bit with Vercel on my own. My discord is Makimian (238688168763850752). I tried using Vercel in one of my other repositories and it seems to be functioning. If you have time to check out the integration and see if you can spot any problems I would greatly appreciate it, https://github.com/MaximilianAdF/Leetcode-Stats. 

I will merge this pull request

**Comment by BobDotCom** [comment]
> @BobDotCom Sorry for the extremely late response, I have been busy lately and have also been experimenting a bit with Vercel on my own. My discord is Makimian (238688168763850752). I tried using Vercel in one of my other repositories and it seems to be functioning. If you have time to check out the integration and see if you can spot any problems I would greatly appreciate it, https://github.com/MaximilianAdF/Leetcode-Stats.
> 
> I will merge this pull request

@MaximilianAdF I'll take a look at it, and I also added/messaged you on discord. I'll send you some other info on the configuration though there.

**Pull request merged**
